# Generated by Django 2.2.16 on 2023-07-20 18:27

import colorfield.fields
from django.db import migrations, models
import shop.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, unique=True, validators=[shop.validator.is_valid_hexa_code])),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='CardShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='media/recipes/images/')),
                ('tags', models.ManyToManyField(max_length=100, to='shop.Tag')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Одежда',
                'ordering': ('name',),
            },
        ),
    ]
