# Generated by Django 2.2.16 on 2023-09-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(default=None, upload_to='grup/img/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CardShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='shouse/')),
                ('tag', models.CharField(choices=[('Shoes', 'Shoes'), ('Socks', 'Socks'), ('Underpants', 'Underpants'), ('Trousers', 'Trousers'), ('Shorts', 'Shorts'), ('T-shirt', 'T-shirt'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket'), ('Sweater', 'Sweater')], max_length=100)),
                ('prise', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, help_text='Магазин к которому будет относиться этот лот', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_card', to='shop.Group')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Одежда',
                'ordering': ('name',),
            },
        ),
    ]
