# Generated by Django 2.2.16 on 2023-07-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardshopitem',
            name='description',
            field=models.TextField(),
        ),
    ]
