# Generated by Django 2.2.16 on 2023-07-20 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230720_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазин',
                'ordering': ('title',),
            },
        ),
        migrations.RemoveField(
            model_name='cardshopitem',
            name='slug',
        ),
        migrations.AddField(
            model_name='cardshopitem',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Магазин к которому будет относиться этот лот', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_card', to='shop.Group'),
        ),
    ]
