# Generated by Django 2.2.16 on 2023-07-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230720_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('title',), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AddField(
            model_name='cardshopitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardshopitem',
            name='prise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardshopitem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
