# Generated by Django 2.2.16 on 2023-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230721_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardshopitem',
            name='tags',
        ),
        migrations.AddField(
            model_name='cardshopitem',
            name='tag',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Socks', 'Socks'), ('Underpants', 'Underpants'), ('Trousers', 'Trousers'), ('Shorts', 'Shorts'), ('T-shirt', 'T-shirt'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket'), ('Sweater', 'Sweater')], default='Sweater', max_length=100),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
