# Generated by Django 2.2.16 on 2023-07-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230721_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardshopitem',
            name='tag',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Socks', 'Socks'), ('Underpants', 'Underpants'), ('Trousers', 'Trousers'), ('Shorts', 'Shorts'), ('T-shirt', 'T-shirt'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket'), ('Sweater', 'Sweater')], max_length=100),
        ),
    ]
