# Generated by Django 2.2.16 on 2023-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20230721_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(default=None, upload_to='images/grup/'),
        ),
        migrations.AlterField(
            model_name='cardshopitem',
            name='image',
            field=models.ImageField(upload_to='images/shouse/'),
        ),
    ]
