# Generated by Django 2.2.16 on 2023-07-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20230721_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default=None, upload_to='grup/img/'),
        ),
    ]
