# Generated by Django 2.2.16 on 2023-07-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20230721_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gif',
            field=models.ImageField(upload_to='grup/gif/'),
        ),
    ]
