# Generated by Django 2.2.16 on 2023-07-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20230721_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='gif',
        ),
        migrations.AddField(
            model_name='group',
            name='gif_m',
            field=models.ImageField(default=None, upload_to='grup/img/'),
        ),
    ]
